# Generated by Django 5.2 on 2025-06-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_adminuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='parament_address',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='present_address',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
